### PR TITLE
Fix accuracy in angle computation

### LINKED ISSUE #222: math_utils angle between almost identical points returns nan
python 3.8
tested on version 1.2.20, but did not see a fix in more recent version
Screenshot 2022-09-23 at 14 29 57

### PR DESCRIPTION
**Pull request by mcara**
This PR is an alternative to #223 and it builds upon it. While I kept _significant_ simplifications in the vector formulas (dot product of two cross products) proposed by @perrygreenfield in #223, I also reduced the number of calls to the `sqrt` function to normalize the cross products entering the dot product.

This was done because it turns out that the main source of "erratic values" in the 2nd double in the quad comes from the `sqrt` function. I have tried to keep the same algorithm and increase accuracy of computations but it still did not solve the issue completely: it only reduced the occurrence of these erratic values but did not eliminate them.

On the other hand, a complete replacement of the algorithm in the `sqrt` function with the Heron's method resulted in a much more stable algorithm (albeit it is likely slower than the original multiply-add algorithm). I kept the checks that @perrygreenfield introduced for the case when the 1st double is +/- 1 but do not use `fabs` as values smaller than 1 in magnitude could still be legitimate values.

Also, the formula for computing conjugate angles was slightly improved in the accuracy.

I have arrived at the conclusion that the  "erratic values" are not due to bugs in the `qd` library but rather a limitation of the accuracy of quad numbers: the original paper by the authors of the `qd` library says that at least 212 bits should be significant. This means that quad numbers have about 64 significant digits, in agreement with observed magnitudes of the erratic values in the second double (<1e-65). Instead on relying on a hard-coded value, this PR uses `epsilon()` value provided by the quad library (which is hardcoded though).

Closes #222

### CODE REVIEW

**Comment by mcara** [comment]
Also, there are many other functions that compute unnecessary cross products and those computations should be reviewed in a separate PR.

**Comment by pllim** [comment]
Add that test? 😉

**Comment by mcara** [comment]
@pllim Working on it right now. Patience, my friend.

**Comment by mcara** [comment]
@pllim See second commit

**Review by pllim — COMMENTED** [review]
I am not worthy to review this but I appreciate you adding a test. 😸

File: src/math_util.c [hunk 1]
```diff
@@ -166,6 +167,48 @@ dot_qd(const qd *A, const qd *B, qd *C) {
...
+    double *v0 = dot_val->x;
+    double *v1 = dot_val->x + 1;
+    double eps = 10.0 * c_qd_epsilon();
+
+    dot_qd(A, A, &aa);
+    dot_qd(B, B, &bb);
+    dot_qd(A, B, &ab);
+    c_qd_mul(aa.x, bb.x, aabb);
+
+    if (aabb[0] < -0.0) {
```
Comment (perrygreenfield) [inline src/math_util.c:188]: I don't understand this part where the product of the dot products of each vector is computed. In principle each dot product should be positive (or zero), but never negative, and yet there is a test for a negative value. If there is a way for the dot product to be negative through a bug, then both might be negative. And what does this have to do with normalizing with regard to the dot of A and B? I am missing something.

**Review by perrygreenfield — COMMENTED** [review]
I also wish there was a way to partition changes made due to PEP8 changes and actual code changes. The PEP8 changes make it harder to see the code changes. Two separate PRs?

File: src/math_util.c (hunk 1 above)
Comment (mcara) [reply src/math_util.c:188]: > And what does this have to do with normalizing with regard to the dot of A and B? I am missing something.

It has nothing to do with normalizing with regard to the dot of A and B. Yes, you are missing the comment above the function:

> normalized_dot_qd returns dot product of **normalized input vectors**.

The original code was doing this:
```
Anormalized = A / SQRT(A.A)
Bnormalized = B / SQRT(B.B)
AB = Anormalized.Bnormalized
```

Modified code does this:
```
AB = A.B / SQRT((A.A)*(B.B))
```

Comment (perrygreenfield) [reply src/math_util.c:188]: So I was missing something.

**Review by perrygreenfield — APPROVED** [review]
Looks Stupendous To Me
